name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature? When would it be helpful?
      placeholder: "This would be useful when..."
    validations:
      required: true

  - type: dropdown
    id: target
    attributes:
      label: Target Platform
      description: Which platform(s) should this feature be available on?
      multiple: true
      options:
        - Browser Extension (Chrome/Firefox)
        - Userscript
        - Both
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I could also..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, examples, or additional information?
      placeholder: "You can attach images by dragging them here"
